### PR TITLE
Update cue to v0.5.0

### LINKED ISSUE #77: Update CUE Go packages to v0.5.0
https://github.com/cue-lang/cue/releases/tag/v0.5.0

### PR DESCRIPTION
**Pull request by uhthomas**
Fixes #77

### CODE REVIEW

**Comment by stefanprodan** [comment]
This breaks `let` according to https://github.com/cue-lang/cue/issues/2351 and https://github.com/cue-lang/cue/issues/2355

But Ok I'm for merging this,  delaying this would being even more issues to Timoni's users who may already upgraded to 0.5.

**Comment by uhthomas** [comment]
@stefanprodan We could use [v0.6.0-alpha.1](https://github.com/cue-lang/cue/releases/tag/v0.6.0-alpha.1).

**Comment by uhthomas** [comment]
Or, I guess those two issues would still not be fixed by that.

**Comment by stefanprodan** [comment]
I'm not considering using an alpha release, also I'm really confused about CUE release cycle, are they going to ship both v0.5 and v0.6 patches, will bug fixes from 0.5.x make in 0.6.x, who knows. To your point, 0.6 does not fixes any of those issue as far as I can tell.

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @uhthomas

**Pull request merged**
