### PR TITLE
fix(doc): Fix typo on "Push to GitHub Container Registry"

### PR DESCRIPTION
**Pull request by yyvess**

### CODE REVIEW

**Comment by stefanprodan** [comment]
@yyvess could you please port the fixes here too, https://github.com/stefanprodan/timoni/blob/main/docs/cue/module/github-actions.md

Thank you!

**Comment by yyvess** [comment]
@stefanprodan You point the file that I am modified modify ;-)

**Comment by stefanprodan** [comment]
There are 2 files, one in the docs root and one in docs/cue/module

**Review by stefanprodan — APPROVED** [review]
LGTM

Thanks @yyvess 🏅

**Pull request merged**
